//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Common.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelBooking.Common.ResourceFiles.TitleResource", typeof(TitleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No info about this apartment.
        /// </summary>
        public static string ApartmentNoInfo {
            get {
                return ResourceManager.GetString("ApartmentNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of rooms.
        /// </summary>
        public static string ApartmentRoomsCount {
            get {
                return ResourceManager.GetString("ApartmentRoomsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of apartment.
        /// </summary>
        public static string ApartmentRoomType {
            get {
                return ResourceManager.GetString("ApartmentRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrival date.
        /// </summary>
        public static string BookingApartmentArrivalDate {
            get {
                return ResourceManager.GetString("BookingApartmentArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Departure date.
        /// </summary>
        public static string BookingApartmentDepartureDate {
            get {
                return ResourceManager.GetString("BookingApartmentDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string MessageOk {
            get {
                return ResourceManager.GetString("MessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The hotel is free now!.
        /// </summary>
        public static string NotificationMessageForApartmentIsFreeNow {
            get {
                return ResourceManager.GetString("NotificationMessageForApartmentIsFreeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your rent is ending.
        /// </summary>
        public static string NotificationMessageForEndingOfBooking {
            get {
                return ResourceManager.GetString("NotificationMessageForEndingOfBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Have an account?.
        /// </summary>
        public static string QuestionHaveAnAccount {
            get {
                return ResourceManager.GetString("QuestionHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No account?.
        /// </summary>
        public static string QuestionNoAccount {
            get {
                return ResourceManager.GetString("QuestionNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notify me?.
        /// </summary>
        public static string QuestionNotifyUser {
            get {
                return ResourceManager.GetString("QuestionNotifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm your password.
        /// </summary>
        public static string RegistrationConfirmPassword {
            get {
                return ResourceManager.GetString("RegistrationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some dates are occupied.
        /// </summary>
        public static string ValidationMessageForBookingOnOccupiedDates {
            get {
                return ResourceManager.GetString("ValidationMessageForBookingOnOccupiedDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not be a same day.
        /// </summary>
        public static string ValidationMessageForBookingOnSameDates {
            get {
                return ResourceManager.GetString("ValidationMessageForBookingOnSameDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong input.
        /// </summary>
        public static string ValidationMessageForBookingOnWrongInput {
            get {
                return ResourceManager.GetString("ValidationMessageForBookingOnWrongInput", resourceCulture);
            }
        }
    }
}
